DROP table IF EXISTS E CASCADE

CREATE TABLE E AS SELECT i AS i,j AS j, 1 AS p, v AS v FROM small_graph

DROP table IF EXISTS R1 CASCADE

CREATE TABLE R1 AS SELECT 1 AS d, i AS i, j AS j, sum(p) AS p, max(v) AS v FROM E GROUP BY d,i,j

DROP table IF EXISTS R2 CASCADE

CREATE TABLE R2 AS SELECT  2 AS d, R1.i AS i, E.j AS j, sum(R1.p*E.p) AS p, max(R1.v+E.v) AS v FROM R1 JOIN E ON R1.j=E.i WHERE R1.i!=R1.j GROUP BY R1.d,R1.i,E.j

SELECT COUNT(*) FROM R2

DROP table IF EXISTS R3 CASCADE

CREATE TABLE R3 AS SELECT  3 AS d, R2.i AS i, E.j AS j, sum(R2.p*E.p) AS p, max(R2.v+E.v) AS v FROM R2 JOIN E ON R2.j=E.i WHERE R2.i!=R2.j GROUP BY R2.d,R2.i,E.j

SELECT COUNT(*) FROM R3

DROP table IF EXISTS R4 CASCADE

CREATE TABLE R4 AS SELECT  4 AS d, R3.i AS i, E.j AS j, sum(R3.p*E.p) AS p, max(R3.v+E.v) AS v FROM R3 JOIN E ON R3.j=E.i WHERE R3.i!=R3.j GROUP BY R3.d,R3.i,E.j

SELECT COUNT(*) FROM R4

DROP table IF EXISTS R5 CASCADE

CREATE TABLE R5 AS SELECT  5 AS d, R4.i AS i, E.j AS j, sum(R4.p*E.p) AS p, max(R4.v+E.v) AS v FROM R4 JOIN E ON R4.j=E.i WHERE R4.i!=R4.j GROUP BY R4.d,R4.i,E.j

SELECT COUNT(*) FROM R5

DROP table IF EXISTS R6 CASCADE

CREATE TABLE R6 AS SELECT  6 AS d, R5.i AS i, E.j AS j, sum(R5.p*E.p) AS p, max(R5.v+E.v) AS v FROM R5 JOIN E ON R5.j=E.i WHERE R5.i!=R5.j GROUP BY R5.d,R5.i,E.j

SELECT COUNT(*) FROM R6

DROP table IF EXISTS R7 CASCADE

CREATE TABLE R7 AS SELECT  7 AS d, R6.i AS i, E.j AS j, sum(R6.p*E.p) AS p, max(R6.v+E.v) AS v FROM R6 JOIN E ON R6.j=E.i WHERE R6.i!=R6.j GROUP BY R6.d,R6.i,E.j

SELECT COUNT(*) FROM R7

DROP table IF EXISTS R8 CASCADE

CREATE TABLE R8 AS SELECT  8 AS d, R7.i AS i, E.j AS j, sum(R7.p*E.p) AS p, max(R7.v+E.v) AS v FROM R7 JOIN E ON R7.j=E.i WHERE R7.i!=R7.j GROUP BY R7.d,R7.i,E.j

SELECT COUNT(*) FROM R8

DROP table IF EXISTS R9 CASCADE

CREATE TABLE R9 AS SELECT  9 AS d, R8.i AS i, E.j AS j, sum(R8.p*E.p) AS p, max(R8.v+E.v) AS v FROM R8 JOIN E ON R8.j=E.i WHERE R8.i!=R8.j GROUP BY R8.d,R8.i,E.j

SELECT COUNT(*) FROM R9

DROP table IF EXISTS R10 CASCADE

CREATE TABLE R10 AS SELECT  10 AS d, R9.i AS i, E.j AS j, sum(R9.p*E.p) AS p, max(R9.v+E.v) AS v FROM R9 JOIN E ON R9.j=E.i WHERE R9.i!=R9.j GROUP BY R9.d,R9.i,E.j

SELECT COUNT(*) FROM R10

DROP table IF EXISTS equ CASCADE

CREATE TABLE equ AS SELECT   * FROM R1 UNION ALL SELECT * FROM R2 UNION ALL SELECT * FROM R3 UNION ALL SELECT * FROM R4 UNION ALL SELECT * FROM R5 UNION ALL SELECT * FROM R6 UNION ALL SELECT * FROM R7 UNION ALL SELECT * FROM R8 UNION ALL SELECT * FROM R9 UNION ALL SELECT * FROM R10

SELECT COUNT(*) FROM equ

DROP table IF EXISTS E CASCADE

DROP table IF EXISTS R1 CASCADE

DROP table IF EXISTS R2 CASCADE

DROP table IF EXISTS R3 CASCADE

DROP table IF EXISTS R4 CASCADE

DROP table IF EXISTS R5 CASCADE

DROP table IF EXISTS R6 CASCADE

DROP table IF EXISTS R7 CASCADE

DROP table IF EXISTS R8 CASCADE

DROP table IF EXISTS R9 CASCADE

DROP table IF EXISTS R10 CASCADE

DROP table IF EXISTS def CASCADE

select d,i,j,sum(p) as p,max(v) as v into def from EQU group by d,i,j

